import {MigrationInterface, QueryRunner} from "typeorm";

export class initializeDatabase1590963627089 implements MigrationInterface {
    name = 'initializeDatabase1590963627089'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "ability" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" character varying(255) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastChangedBy" character varying(255) NOT NULL, "internalComment" character varying(255), CONSTRAINT "PK_5643559d435d01ec126981417a2" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "passive" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" character varying(255) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastChangedBy" character varying(255) NOT NULL, "internalComment" character varying(255), CONSTRAINT "PK_4bbd16160a537c20724636f74e4" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "modifier" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" character varying(255) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastChangedBy" character varying(255) NOT NULL, "internalComment" character varying(255), CONSTRAINT "PK_30c20db2bc7a8c2318b4db0dfc0" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "ancestry" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" character varying(255) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastChangedBy" character varying(255) NOT NULL, "internalComment" character varying(255), CONSTRAINT "PK_cc8f8a92d5918e1091e61241e21" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "background" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" character varying(255) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastChangedBy" character varying(255) NOT NULL, "internalComment" character varying(255), CONSTRAINT "PK_7271b4d2e4bd0f68b3fdb5c090a" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "class" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" character varying(255) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastChangedBy" character varying(255) NOT NULL, "internalComment" character varying(255), CONSTRAINT "PK_0b9024d21bdfba8b1bd1c300eae" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "character" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" character varying(255) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastChangedBy" character varying(255) NOT NULL, "internalComment" character varying(255), CONSTRAINT "PK_6c4aec48c564968be15078b8ae5" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "interactable" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" character varying(255) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastChangedBy" character varying(255) NOT NULL, "internalComment" character varying(255), CONSTRAINT "PK_db5a76ba4bcd14ce1fba1e47c16" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "world" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" character varying(255) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastChangedBy" character varying(255) NOT NULL, "internalComment" character varying(255), CONSTRAINT "PK_9a0e469d5311d0d95ce1202c990" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "ancestry_abilities_ability" ("ancestryId" uuid NOT NULL, "abilityId" uuid NOT NULL, CONSTRAINT "PK_ebd91a4b23c1ef8f2a4be0beb53" PRIMARY KEY ("ancestryId", "abilityId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_5890ca051666e4711873184262" ON "ancestry_abilities_ability" ("ancestryId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_a1e297980f2e5a12098751b28b" ON "ancestry_abilities_ability" ("abilityId") `, undefined);
        await queryRunner.query(`CREATE TABLE "ancestry_passives_passive" ("ancestryId" uuid NOT NULL, "passiveId" uuid NOT NULL, CONSTRAINT "PK_971e7c3fabe466e68e7ee4c19ec" PRIMARY KEY ("ancestryId", "passiveId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_e533ee83aace20bfc1fa615687" ON "ancestry_passives_passive" ("ancestryId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_c55bfea9fb54913bd2e1d5772e" ON "ancestry_passives_passive" ("passiveId") `, undefined);
        await queryRunner.query(`CREATE TABLE "ancestry_modifiers_modifier" ("ancestryId" uuid NOT NULL, "modifierId" uuid NOT NULL, CONSTRAINT "PK_5806d694709e382e8f10b26b38c" PRIMARY KEY ("ancestryId", "modifierId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_803901c7e11a4b4c433c8f70bf" ON "ancestry_modifiers_modifier" ("ancestryId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_b253ebd9eb86f3686f36cf186c" ON "ancestry_modifiers_modifier" ("modifierId") `, undefined);
        await queryRunner.query(`CREATE TABLE "background_abilities_ability" ("backgroundId" uuid NOT NULL, "abilityId" uuid NOT NULL, CONSTRAINT "PK_31e1a08f614b506a1d9121d0d02" PRIMARY KEY ("backgroundId", "abilityId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_99a835f8c8b941e2cadfd23bd6" ON "background_abilities_ability" ("backgroundId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_4c7f2c35af993e7655acac938c" ON "background_abilities_ability" ("abilityId") `, undefined);
        await queryRunner.query(`CREATE TABLE "background_passives_passive" ("backgroundId" uuid NOT NULL, "passiveId" uuid NOT NULL, CONSTRAINT "PK_c079e94c664bc62ae762b432868" PRIMARY KEY ("backgroundId", "passiveId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_448628db5119cc9ad17f95089f" ON "background_passives_passive" ("backgroundId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_15cffec72e688ba97074b038df" ON "background_passives_passive" ("passiveId") `, undefined);
        await queryRunner.query(`CREATE TABLE "background_modifiers_modifier" ("backgroundId" uuid NOT NULL, "modifierId" uuid NOT NULL, CONSTRAINT "PK_3b0b8baaa3cf88724ced55a5e05" PRIMARY KEY ("backgroundId", "modifierId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_76fd67d7575606d9d2eab29a30" ON "background_modifiers_modifier" ("backgroundId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_29259f0e05c11282e3eaccf0be" ON "background_modifiers_modifier" ("modifierId") `, undefined);
        await queryRunner.query(`CREATE TABLE "class_abilities_ability" ("classId" uuid NOT NULL, "abilityId" uuid NOT NULL, CONSTRAINT "PK_7378ec43620beff13b5bb3c1039" PRIMARY KEY ("classId", "abilityId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_990030d31f9c590a8c8b49b83a" ON "class_abilities_ability" ("classId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_bdff70454680f700e4a0750bef" ON "class_abilities_ability" ("abilityId") `, undefined);
        await queryRunner.query(`CREATE TABLE "class_passives_passive" ("classId" uuid NOT NULL, "passiveId" uuid NOT NULL, CONSTRAINT "PK_896af40e08e06b9ac3453f35636" PRIMARY KEY ("classId", "passiveId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_d20c9d1a33833c4cd7eb03da4f" ON "class_passives_passive" ("classId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_fd953844787a0295a64769ae60" ON "class_passives_passive" ("passiveId") `, undefined);
        await queryRunner.query(`CREATE TABLE "class_modifiers_modifier" ("classId" uuid NOT NULL, "modifierId" uuid NOT NULL, CONSTRAINT "PK_8861d5ba00b29f9c56f7c323a4b" PRIMARY KEY ("classId", "modifierId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_a3a563dae28cb0510e92e62305" ON "class_modifiers_modifier" ("classId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_ec4011f6492cb58020c984bbd0" ON "class_modifiers_modifier" ("modifierId") `, undefined);
        await queryRunner.query(`CREATE TABLE "character_abilities_ancestry" ("characterId" uuid NOT NULL, "ancestryId" uuid NOT NULL, CONSTRAINT "PK_edfe4248dce17966aef6cd57448" PRIMARY KEY ("characterId", "ancestryId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_8415377f9bce2efa26d3d2979d" ON "character_abilities_ancestry" ("characterId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_8a3d788f248ec82302288ba8a0" ON "character_abilities_ancestry" ("ancestryId") `, undefined);
        await queryRunner.query(`CREATE TABLE "character_backgrounds_background" ("characterId" uuid NOT NULL, "backgroundId" uuid NOT NULL, CONSTRAINT "PK_6a50e908ccaeba1e6c2da7a9e7a" PRIMARY KEY ("characterId", "backgroundId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_c6d2504f8da64ae0be9ee5da52" ON "character_backgrounds_background" ("characterId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_f7496008b34c24a2f73e8296ca" ON "character_backgrounds_background" ("backgroundId") `, undefined);
        await queryRunner.query(`CREATE TABLE "character_classes_class" ("characterId" uuid NOT NULL, "classId" uuid NOT NULL, CONSTRAINT "PK_c1b0a959e8b4591472de47262d3" PRIMARY KEY ("characterId", "classId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_2ff9084a1927b98afb7c0eb2e3" ON "character_classes_class" ("characterId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_16f8fcdd0dacfde1f07124e03f" ON "character_classes_class" ("classId") `, undefined);
        await queryRunner.query(`CREATE TABLE "interactable_abilities_ancestry" ("interactableId" uuid NOT NULL, "ancestryId" uuid NOT NULL, CONSTRAINT "PK_2df155b17817a7c08ca3cb08382" PRIMARY KEY ("interactableId", "ancestryId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_8de87d4edda200be58dda9f8f0" ON "interactable_abilities_ancestry" ("interactableId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_484b805e6bf6f3e37004dbb6e6" ON "interactable_abilities_ancestry" ("ancestryId") `, undefined);
        await queryRunner.query(`CREATE TABLE "interactable_backgrounds_background" ("interactableId" uuid NOT NULL, "backgroundId" uuid NOT NULL, CONSTRAINT "PK_d109ba418810428935e02248761" PRIMARY KEY ("interactableId", "backgroundId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_ac420d0715bac3ccd335416371" ON "interactable_backgrounds_background" ("interactableId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_fb1e7cca0bfd9e04832d47d1f9" ON "interactable_backgrounds_background" ("backgroundId") `, undefined);
        await queryRunner.query(`CREATE TABLE "interactable_classes_class" ("interactableId" uuid NOT NULL, "classId" uuid NOT NULL, CONSTRAINT "PK_4a3db13cd586dfb99934155da50" PRIMARY KEY ("interactableId", "classId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_e1b6f70ae396d81c2c68c686e6" ON "interactable_classes_class" ("interactableId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_68635e759e63d7bd2b6e8e4556" ON "interactable_classes_class" ("classId") `, undefined);
        await queryRunner.query(`CREATE TABLE "world_abilities_ancestry" ("worldId" uuid NOT NULL, "ancestryId" uuid NOT NULL, CONSTRAINT "PK_a309bee77867351c88ea44472d3" PRIMARY KEY ("worldId", "ancestryId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_c3f2971ea39fcc2787a6c8e366" ON "world_abilities_ancestry" ("worldId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_caa5b6c3e9a8d231d25c31317b" ON "world_abilities_ancestry" ("ancestryId") `, undefined);
        await queryRunner.query(`CREATE TABLE "world_backgrounds_background" ("worldId" uuid NOT NULL, "backgroundId" uuid NOT NULL, CONSTRAINT "PK_2ab6a7075f919a63e8ce695218d" PRIMARY KEY ("worldId", "backgroundId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_b66a27122c5cb346f1fca12222" ON "world_backgrounds_background" ("worldId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_c600878015b7dbc0ce52c2a717" ON "world_backgrounds_background" ("backgroundId") `, undefined);
        await queryRunner.query(`CREATE TABLE "world_classes_class" ("worldId" uuid NOT NULL, "classId" uuid NOT NULL, CONSTRAINT "PK_4e397e489b1d913244a05af8e47" PRIMARY KEY ("worldId", "classId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_cf32fe99a0e38de901dc92f2d9" ON "world_classes_class" ("worldId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_d8bcd3e2584aa68881a867ad3e" ON "world_classes_class" ("classId") `, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_abilities_ability" ADD CONSTRAINT "FK_5890ca051666e4711873184262e" FOREIGN KEY ("ancestryId") REFERENCES "ancestry"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_abilities_ability" ADD CONSTRAINT "FK_a1e297980f2e5a12098751b28bf" FOREIGN KEY ("abilityId") REFERENCES "ability"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_passives_passive" ADD CONSTRAINT "FK_e533ee83aace20bfc1fa6156877" FOREIGN KEY ("ancestryId") REFERENCES "ancestry"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_passives_passive" ADD CONSTRAINT "FK_c55bfea9fb54913bd2e1d5772ec" FOREIGN KEY ("passiveId") REFERENCES "passive"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_modifiers_modifier" ADD CONSTRAINT "FK_803901c7e11a4b4c433c8f70bf3" FOREIGN KEY ("ancestryId") REFERENCES "ancestry"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_modifiers_modifier" ADD CONSTRAINT "FK_b253ebd9eb86f3686f36cf186cf" FOREIGN KEY ("modifierId") REFERENCES "modifier"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "background_abilities_ability" ADD CONSTRAINT "FK_99a835f8c8b941e2cadfd23bd68" FOREIGN KEY ("backgroundId") REFERENCES "background"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "background_abilities_ability" ADD CONSTRAINT "FK_4c7f2c35af993e7655acac938c0" FOREIGN KEY ("abilityId") REFERENCES "ability"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "background_passives_passive" ADD CONSTRAINT "FK_448628db5119cc9ad17f95089fe" FOREIGN KEY ("backgroundId") REFERENCES "background"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "background_passives_passive" ADD CONSTRAINT "FK_15cffec72e688ba97074b038dfa" FOREIGN KEY ("passiveId") REFERENCES "passive"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "background_modifiers_modifier" ADD CONSTRAINT "FK_76fd67d7575606d9d2eab29a301" FOREIGN KEY ("backgroundId") REFERENCES "background"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "background_modifiers_modifier" ADD CONSTRAINT "FK_29259f0e05c11282e3eaccf0bef" FOREIGN KEY ("modifierId") REFERENCES "modifier"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "class_abilities_ability" ADD CONSTRAINT "FK_990030d31f9c590a8c8b49b83a8" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "class_abilities_ability" ADD CONSTRAINT "FK_bdff70454680f700e4a0750befd" FOREIGN KEY ("abilityId") REFERENCES "ability"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "class_passives_passive" ADD CONSTRAINT "FK_d20c9d1a33833c4cd7eb03da4f1" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "class_passives_passive" ADD CONSTRAINT "FK_fd953844787a0295a64769ae606" FOREIGN KEY ("passiveId") REFERENCES "passive"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "class_modifiers_modifier" ADD CONSTRAINT "FK_a3a563dae28cb0510e92e623059" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "class_modifiers_modifier" ADD CONSTRAINT "FK_ec4011f6492cb58020c984bbd0f" FOREIGN KEY ("modifierId") REFERENCES "modifier"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "character_abilities_ancestry" ADD CONSTRAINT "FK_8415377f9bce2efa26d3d2979d0" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "character_abilities_ancestry" ADD CONSTRAINT "FK_8a3d788f248ec82302288ba8a06" FOREIGN KEY ("ancestryId") REFERENCES "ancestry"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "character_backgrounds_background" ADD CONSTRAINT "FK_c6d2504f8da64ae0be9ee5da52f" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "character_backgrounds_background" ADD CONSTRAINT "FK_f7496008b34c24a2f73e8296cab" FOREIGN KEY ("backgroundId") REFERENCES "background"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "character_classes_class" ADD CONSTRAINT "FK_2ff9084a1927b98afb7c0eb2e38" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "character_classes_class" ADD CONSTRAINT "FK_16f8fcdd0dacfde1f07124e03f9" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_abilities_ancestry" ADD CONSTRAINT "FK_8de87d4edda200be58dda9f8f02" FOREIGN KEY ("interactableId") REFERENCES "interactable"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_abilities_ancestry" ADD CONSTRAINT "FK_484b805e6bf6f3e37004dbb6e62" FOREIGN KEY ("ancestryId") REFERENCES "ancestry"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_backgrounds_background" ADD CONSTRAINT "FK_ac420d0715bac3ccd335416371f" FOREIGN KEY ("interactableId") REFERENCES "interactable"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_backgrounds_background" ADD CONSTRAINT "FK_fb1e7cca0bfd9e04832d47d1f90" FOREIGN KEY ("backgroundId") REFERENCES "background"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_classes_class" ADD CONSTRAINT "FK_e1b6f70ae396d81c2c68c686e66" FOREIGN KEY ("interactableId") REFERENCES "interactable"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_classes_class" ADD CONSTRAINT "FK_68635e759e63d7bd2b6e8e4556a" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "world_abilities_ancestry" ADD CONSTRAINT "FK_c3f2971ea39fcc2787a6c8e366c" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "world_abilities_ancestry" ADD CONSTRAINT "FK_caa5b6c3e9a8d231d25c31317b5" FOREIGN KEY ("ancestryId") REFERENCES "ancestry"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "world_backgrounds_background" ADD CONSTRAINT "FK_b66a27122c5cb346f1fca122224" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "world_backgrounds_background" ADD CONSTRAINT "FK_c600878015b7dbc0ce52c2a7177" FOREIGN KEY ("backgroundId") REFERENCES "background"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "world_classes_class" ADD CONSTRAINT "FK_cf32fe99a0e38de901dc92f2d91" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "world_classes_class" ADD CONSTRAINT "FK_d8bcd3e2584aa68881a867ad3e4" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "world_classes_class" DROP CONSTRAINT "FK_d8bcd3e2584aa68881a867ad3e4"`, undefined);
        await queryRunner.query(`ALTER TABLE "world_classes_class" DROP CONSTRAINT "FK_cf32fe99a0e38de901dc92f2d91"`, undefined);
        await queryRunner.query(`ALTER TABLE "world_backgrounds_background" DROP CONSTRAINT "FK_c600878015b7dbc0ce52c2a7177"`, undefined);
        await queryRunner.query(`ALTER TABLE "world_backgrounds_background" DROP CONSTRAINT "FK_b66a27122c5cb346f1fca122224"`, undefined);
        await queryRunner.query(`ALTER TABLE "world_abilities_ancestry" DROP CONSTRAINT "FK_caa5b6c3e9a8d231d25c31317b5"`, undefined);
        await queryRunner.query(`ALTER TABLE "world_abilities_ancestry" DROP CONSTRAINT "FK_c3f2971ea39fcc2787a6c8e366c"`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_classes_class" DROP CONSTRAINT "FK_68635e759e63d7bd2b6e8e4556a"`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_classes_class" DROP CONSTRAINT "FK_e1b6f70ae396d81c2c68c686e66"`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_backgrounds_background" DROP CONSTRAINT "FK_fb1e7cca0bfd9e04832d47d1f90"`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_backgrounds_background" DROP CONSTRAINT "FK_ac420d0715bac3ccd335416371f"`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_abilities_ancestry" DROP CONSTRAINT "FK_484b805e6bf6f3e37004dbb6e62"`, undefined);
        await queryRunner.query(`ALTER TABLE "interactable_abilities_ancestry" DROP CONSTRAINT "FK_8de87d4edda200be58dda9f8f02"`, undefined);
        await queryRunner.query(`ALTER TABLE "character_classes_class" DROP CONSTRAINT "FK_16f8fcdd0dacfde1f07124e03f9"`, undefined);
        await queryRunner.query(`ALTER TABLE "character_classes_class" DROP CONSTRAINT "FK_2ff9084a1927b98afb7c0eb2e38"`, undefined);
        await queryRunner.query(`ALTER TABLE "character_backgrounds_background" DROP CONSTRAINT "FK_f7496008b34c24a2f73e8296cab"`, undefined);
        await queryRunner.query(`ALTER TABLE "character_backgrounds_background" DROP CONSTRAINT "FK_c6d2504f8da64ae0be9ee5da52f"`, undefined);
        await queryRunner.query(`ALTER TABLE "character_abilities_ancestry" DROP CONSTRAINT "FK_8a3d788f248ec82302288ba8a06"`, undefined);
        await queryRunner.query(`ALTER TABLE "character_abilities_ancestry" DROP CONSTRAINT "FK_8415377f9bce2efa26d3d2979d0"`, undefined);
        await queryRunner.query(`ALTER TABLE "class_modifiers_modifier" DROP CONSTRAINT "FK_ec4011f6492cb58020c984bbd0f"`, undefined);
        await queryRunner.query(`ALTER TABLE "class_modifiers_modifier" DROP CONSTRAINT "FK_a3a563dae28cb0510e92e623059"`, undefined);
        await queryRunner.query(`ALTER TABLE "class_passives_passive" DROP CONSTRAINT "FK_fd953844787a0295a64769ae606"`, undefined);
        await queryRunner.query(`ALTER TABLE "class_passives_passive" DROP CONSTRAINT "FK_d20c9d1a33833c4cd7eb03da4f1"`, undefined);
        await queryRunner.query(`ALTER TABLE "class_abilities_ability" DROP CONSTRAINT "FK_bdff70454680f700e4a0750befd"`, undefined);
        await queryRunner.query(`ALTER TABLE "class_abilities_ability" DROP CONSTRAINT "FK_990030d31f9c590a8c8b49b83a8"`, undefined);
        await queryRunner.query(`ALTER TABLE "background_modifiers_modifier" DROP CONSTRAINT "FK_29259f0e05c11282e3eaccf0bef"`, undefined);
        await queryRunner.query(`ALTER TABLE "background_modifiers_modifier" DROP CONSTRAINT "FK_76fd67d7575606d9d2eab29a301"`, undefined);
        await queryRunner.query(`ALTER TABLE "background_passives_passive" DROP CONSTRAINT "FK_15cffec72e688ba97074b038dfa"`, undefined);
        await queryRunner.query(`ALTER TABLE "background_passives_passive" DROP CONSTRAINT "FK_448628db5119cc9ad17f95089fe"`, undefined);
        await queryRunner.query(`ALTER TABLE "background_abilities_ability" DROP CONSTRAINT "FK_4c7f2c35af993e7655acac938c0"`, undefined);
        await queryRunner.query(`ALTER TABLE "background_abilities_ability" DROP CONSTRAINT "FK_99a835f8c8b941e2cadfd23bd68"`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_modifiers_modifier" DROP CONSTRAINT "FK_b253ebd9eb86f3686f36cf186cf"`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_modifiers_modifier" DROP CONSTRAINT "FK_803901c7e11a4b4c433c8f70bf3"`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_passives_passive" DROP CONSTRAINT "FK_c55bfea9fb54913bd2e1d5772ec"`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_passives_passive" DROP CONSTRAINT "FK_e533ee83aace20bfc1fa6156877"`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_abilities_ability" DROP CONSTRAINT "FK_a1e297980f2e5a12098751b28bf"`, undefined);
        await queryRunner.query(`ALTER TABLE "ancestry_abilities_ability" DROP CONSTRAINT "FK_5890ca051666e4711873184262e"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_d8bcd3e2584aa68881a867ad3e"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_cf32fe99a0e38de901dc92f2d9"`, undefined);
        await queryRunner.query(`DROP TABLE "world_classes_class"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_c600878015b7dbc0ce52c2a717"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_b66a27122c5cb346f1fca12222"`, undefined);
        await queryRunner.query(`DROP TABLE "world_backgrounds_background"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_caa5b6c3e9a8d231d25c31317b"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_c3f2971ea39fcc2787a6c8e366"`, undefined);
        await queryRunner.query(`DROP TABLE "world_abilities_ancestry"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_68635e759e63d7bd2b6e8e4556"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_e1b6f70ae396d81c2c68c686e6"`, undefined);
        await queryRunner.query(`DROP TABLE "interactable_classes_class"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_fb1e7cca0bfd9e04832d47d1f9"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_ac420d0715bac3ccd335416371"`, undefined);
        await queryRunner.query(`DROP TABLE "interactable_backgrounds_background"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_484b805e6bf6f3e37004dbb6e6"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_8de87d4edda200be58dda9f8f0"`, undefined);
        await queryRunner.query(`DROP TABLE "interactable_abilities_ancestry"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_16f8fcdd0dacfde1f07124e03f"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_2ff9084a1927b98afb7c0eb2e3"`, undefined);
        await queryRunner.query(`DROP TABLE "character_classes_class"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_f7496008b34c24a2f73e8296ca"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_c6d2504f8da64ae0be9ee5da52"`, undefined);
        await queryRunner.query(`DROP TABLE "character_backgrounds_background"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_8a3d788f248ec82302288ba8a0"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_8415377f9bce2efa26d3d2979d"`, undefined);
        await queryRunner.query(`DROP TABLE "character_abilities_ancestry"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_ec4011f6492cb58020c984bbd0"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_a3a563dae28cb0510e92e62305"`, undefined);
        await queryRunner.query(`DROP TABLE "class_modifiers_modifier"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_fd953844787a0295a64769ae60"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_d20c9d1a33833c4cd7eb03da4f"`, undefined);
        await queryRunner.query(`DROP TABLE "class_passives_passive"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_bdff70454680f700e4a0750bef"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_990030d31f9c590a8c8b49b83a"`, undefined);
        await queryRunner.query(`DROP TABLE "class_abilities_ability"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_29259f0e05c11282e3eaccf0be"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_76fd67d7575606d9d2eab29a30"`, undefined);
        await queryRunner.query(`DROP TABLE "background_modifiers_modifier"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_15cffec72e688ba97074b038df"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_448628db5119cc9ad17f95089f"`, undefined);
        await queryRunner.query(`DROP TABLE "background_passives_passive"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_4c7f2c35af993e7655acac938c"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_99a835f8c8b941e2cadfd23bd6"`, undefined);
        await queryRunner.query(`DROP TABLE "background_abilities_ability"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_b253ebd9eb86f3686f36cf186c"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_803901c7e11a4b4c433c8f70bf"`, undefined);
        await queryRunner.query(`DROP TABLE "ancestry_modifiers_modifier"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_c55bfea9fb54913bd2e1d5772e"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_e533ee83aace20bfc1fa615687"`, undefined);
        await queryRunner.query(`DROP TABLE "ancestry_passives_passive"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_a1e297980f2e5a12098751b28b"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_5890ca051666e4711873184262"`, undefined);
        await queryRunner.query(`DROP TABLE "ancestry_abilities_ability"`, undefined);
        await queryRunner.query(`DROP TABLE "world"`, undefined);
        await queryRunner.query(`DROP TABLE "interactable"`, undefined);
        await queryRunner.query(`DROP TABLE "character"`, undefined);
        await queryRunner.query(`DROP TABLE "class"`, undefined);
        await queryRunner.query(`DROP TABLE "background"`, undefined);
        await queryRunner.query(`DROP TABLE "ancestry"`, undefined);
        await queryRunner.query(`DROP TABLE "modifier"`, undefined);
        await queryRunner.query(`DROP TABLE "passive"`, undefined);
        await queryRunner.query(`DROP TABLE "ability"`, undefined);
    }

}
